friends/urls.py
from django.conf.urls import url
from .views import index, add_friend
#from .views import add_activity

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend/', add_friend, name='add_friend'),

]

statistic/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^statistic/$', index, name='index'),
]

status/urls.py
from django.conf.urls import url
from .views import index,status


urlpatterns = [
   url(r'^$', index, name='index'),
   url(r'^status/$', index, name='index'),
   url(r'^add_todo/$', status, name='status'),
]

tugasPPW/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import status.urls as status
import friends.urls as friends
import statistic.urls as statistic
from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(status,namespace='status')),
    url(r'^friends/', include(friends,namespace='friends')),
    url(r'^', include('statistic.urls', namespace='statistic', app_name='statistic')),
    url(r'^$', RedirectView.as_view(url = 'status/', permanent = True),name='index')
]

friends/models.py
from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class AddFriend(models.Model):
	def converTZ():
		return timezone.now() + timezone.timedelta(hours=0)

	name = models.CharField(max_length=27)
	url = models.URLField(max_length=27)
	created_date = models.DateTimeField(default=converTZ)

statistic/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
	title = models.CharField(max_length=27)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

userProfile/models.py
from django.db import models

# Create your models here.

friends/forms.py
from django import forms

class Friend_Form(forms.Form):
	error_messages = {
		'required' : 'Isi input ini',
		'invalid' : 'Isi input ini dengan url'
	}

	name_attrs={
		'type': 'text',
        'class': 'todo-form-input-nameFriend',
        'placeholder':'Nama kamu...'
	}

	url_attrs={
		'type': 'url',
        'class': 'todo-form-input-urlFriend',
        'placeholder':'Url...'
	}

	name = forms.CharField(label='Name', required=True, max_length=100, empty_value='Anonymous', widget=forms.TextInput(attrs=name_attrs))
	url = forms.URLField(label='URL', required=True,max_length=100, empty_value='Anonymous', widget=forms.URLInput(attrs=url_attrs))

status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong input status',
    }
    #title_attrs = {
    #   'type': 'text',
    #   'class': 'todo-form-input',
    #   'placeholder':'Masukan judul...'
    #}

    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Update your status here '
    }

    #title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

friends/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import AddFriend

# Create your views here.
response = {}
def index(request):
    todo = AddFriend.objects.all()
    response['todo'] = todo
    html = 'friends.html'
    response['friend_form'] = Friend_Form
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        todo = AddFriend(name=request.POST['name'],url=request.POST['url'])
        todo.save()
        return HttpResponseRedirect('/friend')

statistic/views.py
from django.shortcuts import render
# from profile_page.models import Profile
from friends.models import AddFriend
from status.models import Todo

# profile = Profile.objects.last()
numb_of_feeds = Todo.objects.count()
numb_of_friends = AddFriend.objects.count()
latest_post = Todo.objects.last()
def index(request):
	response = {'name' : "Deralda", 'feeds' : numb_of_feeds, 'friends' : numb_of_friends, 'latestPost' : latest_post}
	return render(request, 'statistic.html', response)
# Create your views here.

status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):
    response['author'] = "Thrisnadevany" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    # html = 'status.html'
    response['todo_form'] = Todo_Form
    return render(request, 'update.html' , response)

def status(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        #response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/status/')
    else:
        return HttpResponseRedirect('/status/')

userProfile/views.py
from django.shortcuts import render

# Create your views here.

friends/templates/friends.html
{% extends "friends/layout/base.html" %}

{% block content %}
<section id="input">
    <h4 id="h3-add" style="margin-top: 75px">Add Friend</h4>
    <br>
        <form method="POST" action="{% url 'friends:add_friend' %}">
            {% csrf_token %}
            {{friend_form}}
            <br>
            <button style="background-color: #0000FF;margin-left: 90%;width: 100px", type="submit" class="button btn-success">Add Friend</button>
        </form>
</section>
<section id="list-friend">
    <h4 class="friendList">List Friend</h4>
    <div class="friendList">
        {% if todo %}
            {% for data in todo %}
                <div class="col-lg-2">
                    {{data.name}}
                </div>
                <div class="col-lg-2">
                <a href="{{data.url}}">{{data.url}}</a>
                </div>
                <div class="col-lg-2">
                    {{data.created_date}}
                </div>
            {% endfor %}
        {% else %}
        <div class="alert alert-danger text-center bg-info">
            <strong>Oops!</strong> anda belum memiliki teman.
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

friends/templates/friends/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
</head>
<title>
    iunctus.byus
</title>
<body style="background-color:#bbdefb">
	<header>
		{% include "statistic/partials/header.html" %}
	</header>

	<content>
        {% block content %}
            <!-- content goes here -->
        {% endblock %}
    </content>

	<footer>
		{% block footer %}
      	{% include "statistic/partials/footer.html" %}
     	{% endblock %}
	</footer>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
{% block jquery %}
{% endblock %}

statistic/templates/statistic.html
{% extends "statistic/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand+SC|Bitter" rel="stylesheet">
</head>
<style>
	.img-circle {
     border-radius: 50%;
     width: 250px;
     height:250px;
     margin-top: +100px;
     margin-left: +430px;
     float: center;
    }
    .grow:hover{
    -webkit-transform: scale(1.3);
    -ms-transform: scale(1.3);
    transform: scale(1.3);
    }

    #title{
    	font-family: 'Patrick Hand SC', cursive;
    	font-size: 100px;
    	text-align: center;
    }

    #content{
        font-family: 'Bitter', serif;
        font-size: 50px;
        text-align: center;
    }
</style>
<body style="background-color: #b2ebf2">
	<img class= "responsive-img img-circle grow" src="//c1.staticflickr.com/4/3836/14499517289_ab6723c4f1_b.jpg">
    <div class="row">
      <div class="col s12">
          <h2 id = "title">{{ name }}</h2>
      </div>
      <div class="col s6 blue accent-4">
            <h2 id = "title">Friends</h2>
            <p id = "content">{{ friends }} friend</p>
      </div>
      <div class="col s6 blue accent-4">
            <h2 id = "title">Latest Status</h2>
            <p id = "content">{{ latestPost }}</p>
      </div>
      <div class="col s6 red accent-4">
            <h2 id = "title">Numb of Feeds</h2>
            <p id = "content">{{ feeds }} feeds</p>
      </div>
    </div>

</body>
{% endblock %}

statistic/templates/statistic/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/statistic.css' %}" />
</head>
<title>
    iunctus.byus
</title>
<body style="background-color: #bbdefb" class="">
    <header>
        {% include "statistic/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <br>
    <footer>
      {% include "statistic/partials/footer.html" %}
    </footer>

</body>
</html>

statistic/templates/statistic/partials/footer.html
 <p>&copy; 2017 Copyright Text</p>

statistic/templates/statistic/partials/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">.iunctus</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/status/">Status<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/friends/">Add Friend</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/statistic/">Statistic</a>
      </li>
    </ul>
  </div>
</nav>

status/templates/status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
</head>
<title>
    iunctus.byus
</title>
<body style="background-color:#bbdefb">
	<header>
		{% include "statistic/partials/header.html" %}
	</header>

	<content>
        {% block content %}
            <!-- content goes here -->
        {% endblock %}
    </content>

	<footer>
		{% block footer %}
      	{% include "statistic/partials/footer.html" %}
     	{% endblock %}
	</footer>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}

status/templates/table.html
{% extends "lab_4/layout/base.html" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <!--  Populate semua isi pesan dari model -->
    <table class="table">
        <thead>
            <th>Pesan</th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody>

            {% for i in message %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.message}} </td>
                <td> {{i.created_date}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endblock %}

status/templates/update.html
{% extends "status/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
<hr/>
<style type="text/css">
    .todo-form-textarea {
        width: 100%;
    }
    .img-circle {
         border-radius: 50%;
         width: 110px;
         height:110px;
    }
</style>
<div class="container">
    <div class="col">
        <div class="col-sm-6">
            <section name="input-list" id="input-list">
                <div class="container">
                    <form id="form" method="POST" action="{% url 'status:status' %}">
                        <h2>What's on your mind?</h2>
                        <br>
                        {% csrf_token %}
                        {{ todo_form }}

                        <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">

                    </form>
                    <br>

                </div>
            </section>
        </div>
        <div class="col-sm-6">
            <section name="my-list" id="my-list" style="padding-bottom: 20px">


            {% if todo %}
                {% for data in todo %}

                    <div class="container">
                        <div class="row">
                        <div class="col-sm-8 col-sm-offset-2">
                            <div class= "media" style="padding: 40px">
                                <div class= "media-left">
                                    <img class="img-circle"src="https://preview.ibb.co/b8pVNw/06e9350eba304acf094b4d2d67b74870_female_face_drawing_girl_face_drawing.jpg">
                                </div>
                                <div class="media-body" style="padding-left:10px" >

                                    <h4 class="media-heading"><strong>{{author}}</strong> <small><i> Posted on
                                    {{data.created_date}}</i></small></h4>
                                    <p>{{data.description}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>

                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> anda belum memposting status apapun.
            </div>
            {% endif %}
        <!--</div> -->

</section>
        </div>
    </div>
</div>



{% endblock %}